#!/usr/bin/env python
import sys
import rospkg

# messing around with paths to get imports to work
rospack = rospkg.RosPack()
pckg_path = rospack.get_path('velarray')
sys.path.append(pckg_path)

try:
    import src.velarray_driver
except Exception as e:
    raise e

src.velarray_driver.main()
